#include "../include/transport.h"
#include "../include/thermo.h"
#include "thermo.h"
#include "composition.h"
#include "thermo_transport_data.h"
#include "collision_integral_data.h"
#include "../include/math_constants.h"  // MSVC compatibility for M_PI
#include <algorithm>
#include <cmath>
#include <stdexcept>

namespace combaero {

// Transport-related helpers factored out of thermo_transport.cpp.

// Linear interpolation helper for collision integrals
double linear_interp(double x,
                     const std::vector<double>& x_values,
                     const std::vector<double>& y_values)
{
    if (x_values.size() != y_values.size()) {
        throw std::invalid_argument("linear_interp: x_values and y_values must have the same size");
    }
    if (x_values.size() < 2) {
        throw std::invalid_argument("linear_interp: at least two points are required");
    }

    auto it = std::lower_bound(x_values.begin(), x_values.end(), x);

    if (it == x_values.begin()) {
        return y_values.front();
    }
    if (it == x_values.end()) {
        return y_values.back();
    }

    std::size_t idx = static_cast<std::size_t>(std::distance(x_values.begin(), it) - 1);

    double x0 = x_values[idx];
    double x1 = x_values[idx + 1];
    double y0 = y_values[idx];
    double y1 = y_values[idx + 1];

    if (x1 == x0) {
        throw std::invalid_argument("linear_interp: x_values must be strictly increasing");
    }

    double t = (x - x0) / (x1 - x0);
    return y0 + t * (y1 - y0);
}

// Collision integral Omega*(2,2)(T*, delta*): cubic Hermite in
// (ln T*, ln Omega*) on the Monchick-Mason grid, with the node values AND
// slopes from include/collision_integral_data.h (generated by
// thermo_data_generator/collision_integrals.py). delta* = 0 is exact
// Lennard-Jones (quadrature, checked against Kim & Monroe 2014); delta* > 0 is
// Monchick & Mason (1961) with estimated slopes. C1 in T*, so viscosity and
// conductivity have a continuous temperature derivative; linear in delta*,
// which is constant per species. Linear interpolation in raw T* (before
// #485) erred by up to 2.7% between nodes and put 2-17% kinks in dmu/dT.
//
// Outside 0.1 <= T* <= 100 the curve continues linearly in (ln T*, ln Omega*)
// with the end slope (C1 at the edge): a power law, which is the form the
// collision integral takes at both extremes.
namespace {

struct LogTable {
    double lx[collision::kNumTStar];
    double ly[collision::kNumTStar * collision::kNumDelta];
};

const LogTable& log_table() {
    static const LogTable t = [] {
        LogTable r{};
        for (int k = 0; k < collision::kNumTStar; ++k) {
            r.lx[k] = std::log(collision::kTStar[k]);
        }
        for (int k = 0; k < collision::kNumTStar * collision::kNumDelta; ++k) {
            r.ly[k] = std::log(collision::kOmega22[k]);
        }
        return r;
    }();
    return t;
}

// ln Omega* and d ln Omega* / d ln T* in delta* column c at ln T* = lx.
void column_ln_omega(int c, double lx, double& ln_om, double& dln) {
    const LogTable& t = log_table();
    constexpr int nT = collision::kNumTStar;
    constexpr int nD = collision::kNumDelta;
    if (lx <= t.lx[0] || lx >= t.lx[nT - 1]) {
        const int k = (lx <= t.lx[0]) ? 0 : nT - 1;
        dln = collision::kDlnOmega22DlnT[k * nD + c];
        ln_om = t.ly[k * nD + c] + dln * (lx - t.lx[k]);
        return;
    }
    int i = nT - 2;
    for (int k = 0; k < nT - 1; ++k) {
        if (lx <= t.lx[k + 1]) {
            i = k;
            break;
        }
    }
    const double h = t.lx[i + 1] - t.lx[i];
    const double u = (lx - t.lx[i]) / h;
    const double y0 = t.ly[i * nD + c];
    const double y1 = t.ly[(i + 1) * nD + c];
    const double m0 = collision::kDlnOmega22DlnT[i * nD + c] * h;
    const double m1 = collision::kDlnOmega22DlnT[(i + 1) * nD + c] * h;
    const double u2 = u * u;
    const double u3 = u2 * u;
    ln_om = (2 * u3 - 3 * u2 + 1) * y0 + (u3 - 2 * u2 + u) * m0 + (-2 * u3 + 3 * u2) * y1 +
            (u3 - u2) * m1;
    dln = ((6 * u2 - 6 * u) * y0 + (3 * u2 - 4 * u + 1) * m0 + (-6 * u2 + 6 * u) * y1 +
           (3 * u2 - 2 * u) * m1) /
          h;
}

}  // namespace

Omega22Result omega22_and_derivative(double T_star, double delta_star)
{
    constexpr int nD = collision::kNumDelta;
    const double ts = std::max(T_star, 1e-6);
    const double ds = std::max(0.0, std::min(delta_star, collision::kDelta[nD - 1]));
    int iD = nD - 2;
    for (int k = 0; k < nD - 1; ++k) {
        if (ds <= collision::kDelta[k + 1]) {
            iD = k;
            break;
        }
    }
    const double fD = (ds - collision::kDelta[iD]) / (collision::kDelta[iD + 1] - collision::kDelta[iD]);
    const double lx = std::log(ts);
    double l0, d0, l1, d1;
    column_ln_omega(iD, lx, l0, d0);
    column_ln_omega(iD + 1, lx, l1, d1);
    const double om0 = std::exp(l0);
    const double om1 = std::exp(l1);
    Omega22Result r;
    r.omega = (1.0 - fD) * om0 + fD * om1;
    // d Omega/d T* = Omega * (d ln Omega / d ln T*) / T*, per column.
    r.domega_dTstar = ((1.0 - fD) * om0 * d0 + fD * om1 * d1) / ts;
    return r;
}

double omega22(double T_star, double delta_star)
{
    return omega22_and_derivative(T_star, delta_star).omega;
}

// -------------------------------------------------------------
// File-local helpers
// -------------------------------------------------------------

namespace {

// Reduced dipole moment (Stockmayer parameter) delta*.
// well_depth_K in K, diameter_A in Angstrom, dipole_D in Debye.
double compute_delta_star(double well_depth_K, double diameter_A, double dipole_D)
{
    if (dipole_D == 0.0) return 0.0;
    constexpr double K_E     = 8.98755e9;    // N*m^2/C^2  (1/4*pi*eps0)
    constexpr double D_TO_CM = 3.33564e-30;  // C*m per Debye
    const double mu_SI  = dipole_D * D_TO_CM;
    const double eps_SI = well_depth_K * thermo::BOLTZMANN;
    const double sig_m  = diameter_A * 1.0e-10;
    return K_E * mu_SI * mu_SI / (2.0 * eps_SI * sig_m * sig_m * sig_m);
}

struct PureSpeciesTransport {
    std::vector<double> mu;      // pure-species dynamic viscosity [Pa·s]
    std::vector<double> k;       // pure-species thermal conductivity [W/(m·K)]
    std::vector<double> dmu_dT;  // [Pa*s/K], analytic
    std::vector<double> dk_dT;   // [W/(m*K^2)], analytic
};

// Parker temperature correction to Z_rot (Kee 2003 eq. 12.112) and its
// derivative in T*.
double parker_fz(double ts) {
    return 1.0 + std::pow(M_PI, 1.5) / std::sqrt(ts) * (0.5 + 1.0 / ts) +
           (M_PI * M_PI / 4.0 + 2.0) / ts;
}
double parker_fz_dts(double ts) {
    return std::pow(M_PI, 1.5) * (-0.25 * std::pow(ts, -1.5) - 1.5 * std::pow(ts, -2.5)) -
           (M_PI * M_PI / 4.0 + 2.0) / (ts * ts);
}

PureSpeciesTransport pure_species_transport(double T_in, const std::vector<double>& X)
{
    // Below 10 K the state is held (and so is everything derived from it).
    const double T = std::max(T_in, 10.0);
    const double dT_dTin = (T_in > 10.0) ? 1.0 : 0.0;

    const std::size_t N = X.size();
    PureSpeciesTransport out;
    out.mu.resize(N);
    out.k.resize(N);
    out.dmu_dT.resize(N);
    out.dk_dT.resize(N);

    for (std::size_t i = 0; i < N; ++i) {
        const double eps    = transport_props[i].well_depth;
        const double mw_kg  = molar_masses[i] / 1000.0;              // kg/mol
        const double diam   = transport_props[i].diameter * 1.0e-10; // m
        const double T_star = T / eps;
        const double d_star = compute_delta_star(transport_props[i].well_depth,
                                                 transport_props[i].diameter,
                                                 transport_props[i].dipole_moment);
        const Omega22Result om = omega22_and_derivative(T_star, d_star);
        const double m_mol  = mw_kg / thermo::AVOGADRO;              // kg/molecule

        // Kinetic theory viscosity: mu = (5/16) sqrt(pi*m*k_B*T) / (pi*sigma^2*Omega)
        out.mu[i] = (5.0 / 16.0) * std::sqrt(M_PI * m_mol * thermo::BOLTZMANN * T) /
                    (M_PI * diam * diam * om.omega);
        // d ln mu / dT = 1/(2T) - (dOmega/dT*) / (Omega eps)
        const double dlnmu = 0.5 / T - om.domega_dTstar / (om.omega * eps);
        out.dmu_dT[i] = out.mu[i] * dlnmu * dT_dTin;

        // Mason-Monchick modified Eucken thermal conductivity
        // Formula from Kee, Coltrin & Glarborg (2003) as implemented in Cantera.
        // All cv_*_R are dimensionless (in units of R per mole).

        // cv_rot in units of R: nrot/2 (Atom=0, Linear=1, Nonlinear=1.5)
        double cv_rot_R = 0.0;
        switch (transport_props[i].geometry) {
            case MolecularGeometry::Atom:      cv_rot_R = 0.0; break;
            case MolecularGeometry::Linear:    cv_rot_R = 1.0; break;
            case MolecularGeometry::Nonlinear: cv_rot_R = 1.5; break;
        }

        // cv_vib from NASA: cp/R - 5/2 - cv_rot/R (clamp to 0 at low T). The
        // clamp is a kink (H2 below ~350 K); its derivative is one-sided,
        // taken on the branch the value is on.
        const double cv_vib_raw = cp_R(i, T) - 2.5 - cv_rot_R;
        const double cv_vib_R = std::max(0.0, cv_vib_raw);
        const double dcv_vib = (cv_vib_raw > 0.0) ? dcp_R_dT(i, T) : 0.0;

        // rho*D/mu ~ 6/5 (kinetic theory approximation)
        const double f_int_val = 1.2;
        const double A_factor  = 2.5 - f_int_val;  // ~ 1.3

        const double z_rot = transport_props[i].z_rot;
        double z_rot_eff = z_rot;
        double dz_rot = 0.0;
        if (z_rot > 0.0) {
            const double tstar_298 = 298.0 / eps;
            const double fz = parker_fz(T_star);
            z_rot_eff = z_rot * parker_fz(tstar_298) / fz;
            dz_rot = -z_rot_eff * parker_fz_dts(T_star) / fz / eps;
        }

        const double B_factor = z_rot_eff + (2.0 / M_PI) * (5.0 / 3.0 * cv_rot_R + f_int_val);
        const double c1       = (2.0 / M_PI) * A_factor / B_factor;
        const double dc1      = -c1 * dz_rot / B_factor;
        const double f_rot    = f_int_val * (1.0 + c1);
        const double f_trans  = 2.5 * (1.0 - c1 * cv_rot_R / 1.5);

        const double bracket = f_trans * 1.5 + f_rot * cv_rot_R + f_int_val * cv_vib_R;
        const double dbracket = -2.5 * dc1 * cv_rot_R + f_int_val * dc1 * cv_rot_R +
                                f_int_val * dcv_vib;
        const double scale = thermo::R_GAS / mw_kg;
        out.k[i] = out.mu[i] * scale * bracket;
        out.dk_dT[i] = (out.dmu_dT[i] * bracket + out.mu[i] * dbracket * dT_dTin) * scale;
    }

    return out;
}

// Wilke mixing rule for viscosity given pre-computed pure-species μᵢ.
double wilke_viscosity(const std::vector<double>& X,
                       const std::vector<double>& pure_mu)
{
    const std::size_t N = X.size();
    double mix_visc = 0.0;
    for (std::size_t i = 0; i < N; ++i) {
        if (X[i] <= 0.0) continue;
        double denom = 0.0;
        for (std::size_t j = 0; j < N; ++j) {
            if (X[j] <= 0.0) continue;
            double phi_ij;
            if (i == j) {
                phi_ij = 1.0;
            } else {
                const double M_i   = molar_masses[i];
                const double M_j   = molar_masses[j];
                const double term1 = 1.0 / std::sqrt(8.0) / std::sqrt(1.0 + M_i / M_j);
                const double term2 = std::pow(1.0 + std::sqrt(pure_mu[i] / pure_mu[j]) *
                                     std::pow(M_j / M_i, 0.25), 2);
                phi_ij = term1 * term2;
            }
            denom += X[j] * phi_ij;
        }
        mix_visc += X[i] * pure_mu[i] / denom;
    }
    return mix_visc;
}

// Mixture thermal conductivity (average of upper/lower bounds) given pre-computed kᵢ.
double mixture_conductivity(const std::vector<double>& X,
                            const std::vector<double>& pure_k)
{
    double sum1 = 0.0;
    double sum2 = 0.0;
    for (std::size_t i = 0; i < X.size(); ++i) {
        if (X[i] <= 0.0) continue;
        sum1 += X[i] * pure_k[i];
        sum2 += X[i] / pure_k[i];
    }
    return 0.5 * (sum1 + 1.0 / sum2);
}

// d mu_mix / dT for Wilke's rule: mu_mix = sum_i x_i mu_i / D_i with
// D_i = sum_j x_j phi_ij, phi_ij = a_ij (1 + sqrt(mu_i/mu_j) b_ij)^2.
double wilke_viscosity_dT(const std::vector<double>& X, const std::vector<double>& mu,
                          const std::vector<double>& dmu)
{
    const std::size_t N = X.size();
    double out = 0.0;
    for (std::size_t i = 0; i < N; ++i) {
        if (X[i] <= 0.0) continue;
        double D = 0.0;
        double dD = 0.0;
        for (std::size_t j = 0; j < N; ++j) {
            if (X[j] <= 0.0) continue;
            if (i == j) {
                D += X[j];
                continue;
            }
            const double M_i = molar_masses[i];
            const double M_j = molar_masses[j];
            const double a_ij = 1.0 / std::sqrt(8.0) / std::sqrt(1.0 + M_i / M_j);
            const double b_ij = std::pow(M_j / M_i, 0.25);
            const double r = std::sqrt(mu[i] / mu[j]);
            const double dr = 0.5 * r * (dmu[i] / mu[i] - dmu[j] / mu[j]);
            const double g = 1.0 + r * b_ij;
            D += X[j] * a_ij * g * g;
            dD += X[j] * a_ij * 2.0 * g * b_ij * dr;
        }
        out += X[i] * (dmu[i] / D - mu[i] * dD / (D * D));
    }
    return out;
}

// d k_mix / dT for k_mix = (sum x_i k_i + 1 / sum x_i/k_i) / 2.
double mixture_conductivity_dT(const std::vector<double>& X, const std::vector<double>& k,
                               const std::vector<double>& dk)
{
    double s1 = 0.0, s2 = 0.0, ds2 = 0.0;
    for (std::size_t i = 0; i < X.size(); ++i) {
        if (X[i] <= 0.0) continue;
        s1 += X[i] * dk[i];
        s2 += X[i] / k[i];
        ds2 -= X[i] * dk[i] / (k[i] * k[i]);
    }
    return 0.5 * (s1 - ds2 / (s2 * s2));
}

}  // namespace

// Viscosity and thermal conductivity with their analytic temperature
// derivatives (chain through the collision-integral interpolation, the
// modified Eucken factors and both mixing rules).
TransportDerivatives transport_and_dT(double T, double P, const std::vector<double>& X)
{
    (void)P;
    if (X.size() != species_names.size()) {
        throw std::invalid_argument("transport_and_dT: Mole fraction vector size does not match number of species");
    }
    auto ps = pure_species_transport(T, X);
    TransportDerivatives r;
    r.mu = wilke_viscosity(X, ps.mu);
    r.dmu_dT = wilke_viscosity_dT(X, ps.mu, ps.dmu_dT);
    r.k = mixture_conductivity(X, ps.k);
    r.dk_dT = mixture_conductivity_dT(X, ps.k, ps.dk_dT);
    return r;
}

// Dynamic viscosity [Pa·s]
double viscosity(double T, double P, const std::vector<double>& X)
{
    (void)P;
    if (X.size() != species_names.size()) {
        throw std::invalid_argument("viscosity: Mole fraction vector size does not match number of species");
    }
    auto ps = pure_species_transport(T, X);
    return wilke_viscosity(X, ps.mu);
}

// Thermal conductivity [W/(m·K)]
double thermal_conductivity(double T, double P, const std::vector<double>& X)
{
    (void)P;
    if (X.size() != species_names.size()) {
        throw std::invalid_argument("thermal_conductivity: Mole fraction vector size does not match number of species");
    }
    auto ps = pure_species_transport(T, X);
    return mixture_conductivity(X, ps.k);
}

// Prandtl number (dimensionless)
double prandtl(double T, double P, const std::vector<double>& X)
{
    (void)P;
    if (X.size() != species_names.size()) {
        throw std::invalid_argument("prandtl: Mole fraction vector size does not match number of species");
    }
    auto ps  = pure_species_transport(T, X);
    double mu_mix = wilke_viscosity(X, ps.mu);
    double k_mix  = mixture_conductivity(X, ps.k);
    if (k_mix <= 0.0) {
        throw std::runtime_error("prandtl: thermal conductivity must be positive");
    }
    const double MW      = mwmix(X) / 1000.0;   // kg/mol
    const double cp_mass = cp(T, X) / MW;        // J/(kg·K)
    return (cp_mass * mu_mix) / k_mix;
}

// Kinematic viscosity [m²/s]
double kinematic_viscosity(double T, double P, const std::vector<double>& X)
{
    return viscosity(T, P, X) / density(T, P, X);
}

// Thermal diffusivity [m²/s] — α = k / (ρ cp)
double thermal_diffusivity(double T, double P, const std::vector<double>& X)
{
    const double k_mix   = thermal_conductivity(T, P, X);
    const double rho     = density(T, P, X);
    const double MW      = mwmix(X) / 1000.0;
    const double cp_mass = cp(T, X) / MW;
    return k_mix / (rho * cp_mass);
}

// Reynolds number — Re = ρ V L / μ
double reynolds(double T, double P, const std::vector<double>& X, double V, double L)
{
    const double rho_val = density(T, P, X);
    const double mu      = viscosity(T, P, X);
    if (mu <= 0.0) {
        throw std::runtime_error("reynolds: viscosity must be positive");
    }
    return (rho_val * V * L) / mu;
}

// Peclet number (thermal) — Pe = V L / α
double peclet(double T, double P, const std::vector<double>& X, double V, double L)
{
    const double alpha = thermal_diffusivity(T, P, X);
    if (alpha <= 0.0) {
        throw std::runtime_error("peclet: thermal diffusivity must be positive");
    }
    return (V * L) / alpha;
}

// -------------------------------------------------------------
// Transport State Bundle — single-pass implementation
// -------------------------------------------------------------

TransportState transport_state(double T, double P, const std::vector<double>& X) {

    // Single species-loop pass — omega22 called N times total
    auto ps = pure_species_transport(T, X);

    const double mu  = wilke_viscosity(X, ps.mu);
    const double k   = mixture_conductivity(X, ps.k);
    const double rho = density(T, P, X);
    const double MW  = mwmix(X) / 1000.0;   // kg/mol
    const double cp_m = cp(T, X) / MW;      // J/(kg·K)
    const double cv_m = cv(T, X) / MW;      // J/(kg·K)

    TransportState state;
    state.T     = T;
    state.P     = P;
    state.rho   = rho;
    state.mu    = mu;
    state.k     = k;
    state.nu    = mu / rho;
    state.alpha = k / (rho * cp_m);
    state.Pr    = (cp_m * mu) / k;
    state.cp    = cp_m;
    state.cv    = cv_m;
    state.gamma = cp_m / cv_m;
    state.a     = speed_of_sound(T, X);
    return state;
}

} // namespace combaero
